# Generated by Django 4.1.3 on 2022-11-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_subscriptions_subscribed_since'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscribed_to_user',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='subscriber_user',
        ),
        migrations.DeleteModel(
            name='profiles',
        ),
        migrations.DeleteModel(
            name='subscriptions',
        ),
    ]
