# Generated by Django 4.1.3 on 2022-11-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_game', '0003_connect4game_game_complete_connect4game_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect4game',
            name='player1name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='connect4game',
            name='player2name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
